# Generated by Django 3.2.6 on 2021-08-07 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.categoria'),
            preserve_default=False,
        ),
    ]
